//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaceReviewerServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id { get; set; }
        public string placeId { get; set; }
        public string comment { get; set; }
        public string date { get; set; }
        public int userId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
